title: NE Bytes
description: NE Bytes is a free Microsoft Technology Usergroup based in the North East of England
twitter: https://twitter.com/NEBytes
email: nebytes.events@gmail.com
events: https://ti.to/ne-bytes
youtube: https://www.youtube.com/channel/UCz2PY_ZF0eDv19eeOead2UQ
